[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "chessapp"
version = "0.1.0"

[project.scripts]
dataset_validate = "ml.tools.dataset_validate:main"

