services:
  selfplay-runner:
    image: wiremock/wiremock:2.35.0
    command: ["--port","8011","--verbose","--global-response-templating","--disable-request-logging"]
    ports: ["8011:8011"]
    volumes: ["./infra/stubs/selfplay-runner:/home/wiremock"]
  eval-offline:
    image: wiremock/wiremock:2.35.0
    command: ["--port","8012","--verbose","--global-response-templating","--disable-request-logging"]
    ports: ["8012:8012"]
    volumes: ["./infra/stubs/eval-offline:/home/wiremock"]
