services:
  api:
    environment:
      LOGGING_CONFIG: classpath:logback-spring.xml
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_PUBLIC_KEY_LOCATION: file:/opt/dev-keys/rsa-public.pem
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWS_ALGORITHM: RS256
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:
    volumes:
      - ./infra/dev-keys:/opt/dev-keys:ro
    ports:
      - "8080:8080"
