services:
  api:
    environment:
      # Logging fix (um codex-Config zu umgehen)
      LOGGING_CONFIG: classpath:logback-spring.xml

      # >>> DAS ist das Secret, das SecurityConfig verwendet:
      APP_SECURITY_JWT_SECRET: dev-secret

      # Runner-BaseURLs (falls noch nicht gesetzt)
      SELFPLAY_RUNNER_URL: http://selfplay-runner:8011
      EVAL_RUNNER_URL:     http://eval-offline:8012

      # Verhindere Verwirrung: explizit NICHTs für die SPRING_* JWT-Props
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_SECRET:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_PUBLIC_KEY_LOCATION:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:
    ports:
      - "8080:8080"
