services:
  api:
    environment:
      LOGGING_CONFIG: classpath:logback-spring.xml
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_SECRET: dev-secret
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWS_ALGORITHM: HS256
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_PUBLIC_KEY_LOCATION:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:
    ports:
      - "8080:8080"
