server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB:chs}
    username: ${POSTGRES_USER:chs}
    password: ${POSTGRES_PASSWORD:chs_password_change_me}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    baseline-version: 0
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      app: ${app.name:chessapp}
      component: ${app.component:api}
      env: ${APP_ENV:local}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        chs_api_request_seconds: true
      sla:
        http.server.requests: 100ms,300ms,1s,3s,10s
      minimum-expected-value:
        http.server.requests: 1ms
      maximum-expected-value:
        http.server.requests: 30s
logging:
  level:
    root: INFO
    com.chessapp.api: INFO
    org.flywaydb: DEBUG
    # WebClient logging (set env LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_REACTIVE_FUNCTION_CLIENT=DEBUG to override)
    org.springframework.web.reactive.function.client: INFO
  pattern:
    console: "{\"ts\":\"%d{yyyy-MM-dd'T'HH:mm:ss.SSSX}\",\"level\":\"%p\",\"logger\":\"%c{1}\",\"msg\":%m,\"run_id\":\"%X{run_id}\",\"component\":\"training\"}%n"
app:
  security:
    jwt:
       secret: ${APP_SECURITY_JWT_SECRET:eine-lange-zuf채llige-zeichenketteeine-lange-zuf채llige-zeichenkette}
      # Decoder liest das Roh-Secret (kein Base64), siehe SecurityConfig.
  cors:
    allowed-origins: ${FRONTEND_ORIGIN:http://localhost:5173}
    # Hinweis: Die eigentliche JWT-Pr체fung erfolgt 체ber SecurityConfig#jwtDecoder (HS256, Roh-Secret).
chs:
  default-username: ${CHESS_USERNAME:M3NG00S3}
  registry:
    path: ${CHS_REGISTRY_PATH:classpath:registry/registry.json}
  ml:
    base-url: ${ML_BASE_URL:http://ml:8000}
  serve:
    baseUrl: ${CHS_SERVE_BASEURL:http://serve:8001}
chess:
  ingest:
    baseUrl: https://api.chess.com
    s3:
      bucket:
        logs: logs
        reports: reports
      prefix:
        ingest: ingest
