server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB:chs}
    username: ${POSTGRES_USER:chs}
    password: ${POSTGRES_PASSWORD:chs_password_change_me}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    baseline-version: 0
management:
  endpoints.web.exposure.include: health,info,prometheus, env, metrics,beans,mappings, threaddump
  endpoint:
    env:
      show-values: ALWAYS
  endpoint.health.probes.enabled: true
  metrics.tags:
    application: api
    component: api
    username: ${CHESS_USERNAME:M3NG00S3}
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    root: INFO
    com.chessapp.api: INFO
    org.flywaydb: DEBUG
    # WebClient logging (set env LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_REACTIVE_FUNCTION_CLIENT=DEBUG to override)
    org.springframework.web.reactive.function.client: INFO
  pattern:
    console: "{\"ts\":\"%d{yyyy-MM-dd'T'HH:mm:ss.SSSX}\",\"level\":\"%p\",\"logger\":\"%c{1}\",\"msg\":%m,\"run_id\":\"%X{run_id}\",\"component\":\"training\"}%n"
chs:
  default-username: ${CHESS_USERNAME:M3NG00S3}
  ml:
    base-url: ${ML_BASE_URL:http://ml:8000}
  serve:
    baseUrl: ${CHS_SERVE_BASEURL:http://serve:8001}
chess:
  ingest:
    baseUrl: https://api.chess.com
    s3:
      bucket:
        logs: logs
        reports: reports
      prefix:
        ingest: ingest
