server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:chsdb}
    username: ${POSTGRES_USER:chs}
    password: ${POSTGRES_PASSWORD:chs-secret}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    baseline-version: 0
  main:
    allow-bean-definition-overriding: true   # für dev, löst den IngestService-Konflikt

management:
  endpoints.web.exposure.include: health,info,prometheus, env, metrics,beans,mappings, threaddump
  endpoint:
    env:
      show-values: ALWAYS
  endpoint.health.probes.enabled: true
  metrics.tags:
    application: api
    component: api
    username: ${CHESS_USERNAME:M3NG00S3}

logging:
  config: classpath:logback-codex.xml
  level:
    root: INFO
    com.chessapp.api: INFO
    org.flywaydb: DEBUG

chs:
  default-username: ${CHESS_USERNAME:M3NG00S3}

chess:
  ingest:
    baseUrl: https://api.chess.com
    s3:
      bucket:
        logs: logs
        reports: reports
      prefix:
        ingest: ingest