groups:
- name: serve
  rules:
  - alert: PredictHighErrorRate
    expr: sum by(model_id,model_version)(rate(chs_predict_errors_total[5m])) > 0.2
    for: 5m
    labels:
      severity: warning
      team: obs
    annotations:
      summary: "High predict error rate"
      description: "Error rate >20% for 5m"
  - alert: PredictLatencyP95High
    expr: histogram_quantile(0.95, sum by (le,model_id,model_version)(rate(chs_predict_latency_ms_bucket[5m]))) > 150
    for: 10m
    labels:
      severity: warning
      team: obs
    annotations:
      summary: "Predict latency P95 high"
      description: "P95 latency above 150ms for 10m"
  - alert: ModelReloadFailuresSpike
    expr: increase(chs_model_reload_failures_total[30m]) > 3
    labels:
      severity: critical
      team: obs
    annotations:
      summary: "Model reload failures spike"
      description: "More than 3 reload failures within 30m"
