groups:
  - name: chessapp-api-slo
    interval: 30s
    rules:
      - alert: ApiHighErrorRate
        expr: |
          sum(rate(chs_api_requests_total{component="api", outcome!="success"}[5m]))
            /
          sum(rate(chs_api_requests_total{component="api"}[5m])) > 0.05
        for: 5m
        labels:
          severity: page
          app: chessapp
          component: api
        annotations:
          summary: "API error rate >5% (5m)"
          description: |
            Error rate (non-success outcomes) is above 5% for 5 minutes.
            value={{ $value }}

      - alert: ApiHighLatencyP95
        expr: |
          histogram_quantile(
            0.95,
            sum by (le, uri, method) (rate(chs_api_request_seconds_bucket{component="api"}[5m]))
          ) > 1
        for: 5m
        labels:
          severity: warn
          app: chessapp
          component: api
        annotations:
          summary: "API p95 latency > 1s (5m)"
          description: |
            p95 latency over 5 minutes above threshold.
            value={{ $value }}