name: Docs CI

on:
  pull_request:
    paths:
      - "docs/**"
      - "README.md"
      - "scripts/**"
      - "Makefile.docs"
      - ".github/workflows/docs-ci.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prettier check
        uses: actionsx/prettier@v2
        with:
          args: --check "**/*.md"

      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md

      - name: Link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: .markdownlinkcheck.json
          folder-path: docs

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: SSOT check
        run: python3 scripts/docs_ssot_check.py

