name: Docs CI

on:
  pull_request:
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/docs-ci.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Markdownlint (ohne npm -g)
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md

      # Link-Check nur im docs/-Baum (Respektiert .markdownlinkcheck.json)
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: .markdownlinkcheck.json
          folder-path: docs

      # SSOT-Regelprüfung (Python)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: SSOT check
        run: python3 scripts/docs_ssot_check.py
